
[[sec_7]]
== Concepts

[[sec_7.1]]
=== The complex and nuanced nature of the object called 'Security'

In the context of this Recommendation, on a technological level only, security
architectures can be interpreted as:

* security is an architecture,

* security is a design and/or architecture characteristic,

* security is a design and/or architecture criterion,

* security needs to follow some set of design principles for architecture,

When considering an entity of interest, all the security measures form an
architecture by themselves and all the above interpretations should be
considered at the same time.

This security architecture:

* like any, is subject to comply to a number of functional and non-functional
characteristics,

* is therefore subject to the security characteristics itself,

* needs to follow some set of design principles for architecture,

* may be evaluated against various criteria including security criteria.

This approach is partly revealing one aspect of the significant complexity of
the nature of security architecture on a technological level only.

It should be completed with the fundamental issue that despite the fact that
security of some elements in the system can be proved, there is no definite way
to measure and compare security of the whole system.

This will be called the Juvenal security design constraint in reference to the
famous quote: 'sed quis custodiet, ipsos custodet' which can be interpreted as
'who guards the guards'. This security design constraint represents a key 'glass
roof' that may be pushed, may be deformed but doesn't seem to have any
possibility to be pierced.

All the above considerations are part of an even wider context. Indeed, the
theory of design includes three other dimensions of law, ethics and anthropology
that the architect and/or designer needs to consider when developing a design.
Whilst this is clearly important, these dimensions are not in the scope of this
Recommendation, yet they are represented as attributes in the role of the
architect and/or designer in this document.

Whilst there are few well-constructed examples to illustrate the logical
complexity that the above represents, a good example can be found in
<<b-RFC9413>> in a specific context of the Maintaining Robust Protocols.
Robustness is a typical example of a design characteristic that is expressed and
it shows how this 'robustness principle' led to unanticipated interpretations
that led to pitfall putting at test security design principles.
